# Generated by Django 3.2.4 on 2021-06-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_edited_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='edited_review',
            field=models.TextField(blank=True, default='edit'),
            preserve_default=False,
        ),
    ]
