# Generated by Django 3.2.4 on 2021-06-25 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0006_auto_20210624_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ManyToManyField(to='reviews.Speciality', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='excepted',
            name='word',
            field=models.CharField(max_length=50, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='forbidden',
            name='word',
            field=models.CharField(max_length=50, verbose_name='Слово'),
        ),
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='review',
            name='edited_review',
            field=models.TextField(blank=True, verbose_name='Отредактированный текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.CharField(max_length=20, verbose_name='IP адресс'),
        ),
        migrations.AlterField(
            model_name='review',
            name='raw_review',
            field=models.TextField(verbose_name='Текст пользователя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
